site_name: Serendipity_Docs
site_author: '余智杭'
use_directory_urls: false
theme:
  name: material
  language: zh 
  
  palette:  # 设置灯光
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  icon:    # 设置提示框的样式
    admonition:
    repo: fontawesome/brands/git-alt
    note: octicons/tag-16
    abstract: octicons/checklist-16
    info: octicons/info-16
    tip: octicons/squirrel-16
    success: octicons/check-16
    question: octicons/question-16
    warning: octicons/alert-16
    failure: octicons/x-circle-16
    danger: octicons/zap-16
    bug: octicons/bug-16
    example: octicons/beaker-16
    quote: octicons/quote-16

plugins:
  - search
  - mermaid2: # mermaid插件,查看状态流程图
      arguments:
        theme: 'default'  # 可选主题：default, dark, forest, neutral


# 数据库转存
repo_url: https://github.com/SerendipityOne/markdown_publish
repo_name: Serendipity_Docs

# 添加LaTeX语法支持
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown_sub_sup
  - markdown_mark
  - mdx_math  # 添加LaTeX语法支持
  - pymdownx.arithmatex:    # 添加LaTeX语法支持
      generic: true

nav:
  - 主页: index.md
  - 嵌入式: 
    - PID学习:
      - PID入门教程: 嵌入式\PID学习\PID入门教程.md
      - 双环PID: 嵌入式\PID学习\双环PID.md
    - 平衡车: 嵌入式\平衡车\平衡车.md
    - 四轴无人机: 
      - 主控程序: 嵌入式\四轴无人机\主控程序.md
      - 遥控程序: 嵌入式\四轴无人机\遥控程序.md
  - OI:
    - 洛谷刷题: OI\洛谷刷题.md
  - Linux基础:
    - 1.入门命令: Linux基础\1.入门命令.md
    - 2.文本操作: Linux基础\2.文本操作.md
  